### ISSUE TITLE
Missing Bucket.cpp ?

### ISSUE THREAD

**Issue by fukien** [qifanoctave/Grace-Hash-Join#1]
Hi, thank you for your nice work.
It seems that the repo misses a Bucket.cpp file and makefile doesn't work.
Would you mind updating the repo? Thanks.

**Comment by qifannnnnn** [comment]
Updated. It should be working.

**Comment by fukien** [comment]
Thank you for the quick reply.
Maybe the constructor function in Bucket.cpp should be : 
   Bucket::Bucket(Disk *disk) { this->disk = disk; }
Also, the solution.txt is just a ground truth for checking the join result and has nothing to do with the join processing, isn't it?

**Comment by qifannnnnn** [comment]
Yes I updated bucket.cpp again. The previous one is an old version of it. 
And yeah that solution file is just for checking.

**Comment by fukien** [comment]
Got it, thanks.
